name: Deploy ChickenFarm Functions

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '20'
  FUNCTIONAPP_NAME: chickenfarm-func
  FUNCTION_ENDPOINT: https://chickenfarm-func.azurewebsites.net/api/negotiate

jobs:
  deploy-functionapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies (if package.json exists)
        run: |
          cd azure-functions
          if [ -f "package.json" ]; then
            npm install
          fi
          cd ..

      - name: Zip Azure Function project
        run: |
          cd azure-functions
          zip -r ../functionapp.zip *
          cd ..

      - name: List ZIP content
        run: unzip -l functionapp.zip

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTIONAPP_NAME }}
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Ping Function App endpoint
        run: |
          echo "Esperando 10 segundos para asegurar despliegue..."
          sleep 10
          echo "Haciendo ping a ${{ env.FUNCTION_ENDPOINT }}"
          curl -i ${{ env.FUNCTION_ENDPOINT }}
