name: Build and deploy Azure Function App - chickenfarm-func

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          cd azure-functions
          npm install
          cd ..

      - name: Zip the Azure Functions project
        run: |
          cd azure-functions
          zip -r ../functionapp.zip .
          cd ..

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Move zip to root
        run: mv functionapp.zip ../functionapp.zip || mv functionapp/functionapp.zip .

      - name: Deploy to Azure Function App via publish profile
        uses: Azure/functions-action@v1
        with:
          app-name: chickenfarm-func
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
