name: Deploy ChickenFarm Dashboard and Functions

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '20'

jobs:
  deploy-webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build frontend (si aplica)
        run: |
          echo "Construcción del frontend aquí si es necesario"
          # npm run build

  deploy-functionapp:
    runs-on: ubuntu-latest
    needs: deploy-webapp

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies (if package.json exists)
        run: |
          cd azure-functions
          if [ -f "package.json" ]; then
            npm install
          fi
          cd ..

      - name: Zip Azure Function project
        run: |
          cd azure-functions
          zip -r ../functionapp.zip *
          cd ..

      - name: List ZIP content
        run: unzip -l functionapp.zip

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: chickenfarm-func
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
