name: Deploy Azure Function App - chickenfarm-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './azure-functions'  # Asegúrate de que este sea el path correcto

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present

      - name: Zip the Azure Functions project
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Deploy to Azure Function App via publish profile
        uses: Azure/functions-action@v1
        with:
          app-name: 'chickenfarm-func'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CHICKENFUNC }}
          package: release.zip
