name: Deploy Azure Function App - chickenfarm-func

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd azure-functions
          npm install

      - name: Zip the Azure Functions project
        run: |
          cd azure-functions
          zip -r ../functionapp.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: functionapp
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp

      - name: Deploy to Azure Function App via publish profile
        uses: Azure/functions-action@v1
        with:
          app-name: 'chickenfarm-func'
          package: functionapp.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
